services:
  redis:
    build: ./redis-like
    networks:
      internal:
        aliases: [ "redis" ]

  kv:
    build:
      context: ./kv-server
      dockerfile: Dockerfile.dev
    ports: [ "8080:3000" ]
    environment:
      REDIS_URL: http://redis:4000
    depends_on: [ redis ]
    networks: [ internal ]
    volumes:
      - ./kv-server:/app
      - /app/node_modules

networks:
  internal:
    driver: bridge